CREATE TABLE cliente (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(255) NOT NULL,
	qr_code_whats LONGBLOB DEFAULT NULL,
	status_bot VARCHAR(50) DEFAULT 'PARADO',

	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	deleted_at TIMESTAMP
);