CREATE TABLE contato (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	numero_whats VARCHAR(20) NOT NULL,
	nome VARCHAR(255) NOT NULL,
	
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	deleted_at TIMESTAMP
);