CREATE TABLE template_whats (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(255) NOT NULL,
	chave VARCHAR(255) DEFAULT NULL,
	ativo TINYINT(1) DEFAULT 1,
	texto TEXT NOT NULL,
	path_arquivo VARCHAR(255) DEFAULT NULL,

	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	deleted_at TIMESTAMP
);