CREATE TABLE midia (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) NOT NULL DEFAULT (UUID()) UNIQUE,
    tipo VARCHAR(100) NOT NULL,
    arquivo LONGBLOB NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);
CREATE TABLE cliente (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) NOT NULL DEFAULT (UUID()) UNIQUE,
    nome VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);
CREATE TABLE robo_cliente (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) NOT NULL DEFAULT (UUID()) UNIQUE,
    celular_origem VARCHAR(20) NOT NULL,
    status ENUM('PARADO', 'ENVIANDO') DEFAULT 'PARADO',
    cliente_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    FOREIGN KEY (cliente_id) REFERENCES cliente(id)
);
CREATE TABLE usuario (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) NOT NULL DEFAULT (UUID()) UNIQUE,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) DEFAULT NULL,
    login VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    perfil ENUM('OPERACIONAL', 'ADMINISTRADOR', 'ROBO', 'MASTER') DEFAULT 'OPERACIONAL',
    cliente_id BIGINT UNSIGNED DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    FOREIGN KEY (cliente_id) REFERENCES cliente(id)
);
CREATE TABLE tipo_campo_customizado(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) NOT NULL DEFAULT (UUID()) UNIQUE,
    nome VARCHAR(255) NOT NULL,
    mascara VARCHAR(255) NOT NULL,
    cliente_id BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (cliente_id) REFERENCES cliente(id)
);
CREATE TABLE campo_customizado (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) NOT NULL DEFAULT (UUID()) UNIQUE,
    rotulo VARCHAR(255) NOT NULL,
    ativo TINYINT(1) DEFAULT 1,
    obrigatorio TINYINT(1) DEFAULT 0,
    tipo_campo_customizado_id BIGINT UNSIGNED NOT NULL,
    cliente_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    FOREIGN KEY (tipo_campo_customizado_id) REFERENCES tipo_campo_customizado(id),
    FOREIGN KEY (cliente_id) REFERENCES cliente(id)
);
CREATE TABLE contato (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) NOT NULL DEFAULT (UUID()) UNIQUE,
    nome VARCHAR(255) NOT NULL,
    numero_whats VARCHAR(20) DEFAULT NULL,
    cliente_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    FOREIGN KEY (cliente_id) REFERENCES cliente(id)
);
CREATE TABLE contato_campo_customizado (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) NOT NULL DEFAULT (UUID()) UNIQUE,
    valor VARCHAR(255) NOT NULL,
    contato_id BIGINT UNSIGNED NOT NULL,
    campo_customizado_id BIGINT UNSIGNED NOT NULL,
    cliente_id BIGINT UNSIGNED NOT NULL,
    deleted_at TIMESTAMP,
    FOREIGN KEY (contato_id) REFERENCES contato(id),
    FOREIGN KEY (campo_customizado_id) REFERENCES campo_customizado(id),
    FOREIGN KEY (cliente_id) REFERENCES cliente(id)
);
CREATE TABLE setup_envio_whats (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) NOT NULL DEFAULT (UUID()) UNIQUE,
    data_prevista_inicio DATETIME DEFAULT NULL,
    intervalo_entre_mensagem_min INT DEFAULT 15,
    intervalo_entre_mensagem_max INT NOT NULL,
    is_recorrente TINYINT(1) DEFAULT 0,
    dias_recorrencia INT DEFAULT NULL,
    cliente_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    FOREIGN KEY (cliente_id) REFERENCES cliente(id)
);
CREATE TABLE template_whats (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) NOT NULL DEFAULT (UUID()) UNIQUE,
    nome VARCHAR(255) NOT NULL,
    chave VARCHAR(255) DEFAULT NULL,
    ativo TINYINT(1) DEFAULT 1,
    cliente_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    FOREIGN KEY (cliente_id) REFERENCES cliente(id)
);
CREATE TABLE mensagem_whats (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) NOT NULL DEFAULT (UUID()) UNIQUE,
    ordem_envio INT NOT NULL DEFAULT 0,
    texto VARCHAR(255) DEFAULT NULL,
    midia_id BIGINT UNSIGNED DEFAULT NULL,
    template_whats_id BIGINT UNSIGNED NOT NULL,
    cliente_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    FOREIGN KEY (midia_id) REFERENCES midia(id),
    FOREIGN KEY (template_whats_id) REFERENCES template_whats(id),
    FOREIGN KEY (cliente_id) REFERENCES cliente(id)
);
CREATE TABLE envio_whats (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) NOT NULL DEFAULT (UUID()) UNIQUE,
    celular_origem VARCHAR(20) NOT NULL,
    status ENUM(
        'NA_FILA',
        'EM_ANDAMENTO',
        'ENVIADO',
        'CANCELADO',
        'ERRO'
    ) DEFAULT 'NA_FILA',
    log VARCHAR(255) DEFAULT NULL,
    data_real DATETIME DEFAULT NULL,
    contato_id BIGINT UNSIGNED NOT NULL,
    template_whats_id BIGINT UNSIGNED NOT NULL,
    setup_envio_whats_id BIGINT UNSIGNED NOT NULL,
    cliente_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    FOREIGN KEY (contato_id) REFERENCES contato(id),
    FOREIGN KEY (template_whats_id) REFERENCES template_whats(id),
    FOREIGN KEY (setup_envio_whats_id) REFERENCES setup_envio_whats(id),
    FOREIGN KEY (cliente_id) REFERENCES cliente(id)
);